server:
  port: 9001
spring:
  datasource:
      url: jdbc:mysql:///pinyougoudb?userUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
pagehelper:
  helper-dialect: mysql
  params: count=countsql